name: First Workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Greeting
        run: echo "Hello World ankita!!"

      - name: Print Goodbye
        run: echo "Done-Bye"

    
